
# Makefile for libbtdrv.so #
ifeq ($(CONFIG_DEFAULTS_MEDIATEK_MT7623),y)
-include Makefile.combo
endif

ifeq ($(CONFIG_DEFAULTS_MEDIATEK_MT7621),y)
-include Makefile.extusb
endif

ifeq ($(CONFIG_DEFAULTS_MEDIATEK_MT7628),y)
-include Makefile.extusb
endif
